### ISSUE TITLE
Oak theme - Update

### ISSUE THREAD

**Issue by Djokic** [HowtoGhost/allghostthemes#51]
*This is just update for existing Oak theme*

### Theme Name

Oak

### Theme Description

Oak is a simple, elegant and two column theme combined with clean typography to make this theme a perfect companion for your future blogging adventures. Oak helps you to setup a beautiful personal blog as it is suitable for any kind of personal, travel, hobby and idea sharing blog. In addition, Oak helps you to share your thoughts, stories and ideas to this world with no extra effort. Totally, Oak is a fantastic theme for any blog that involves more number of images.

### Link to your live demo

http://oaktheme.herokuapp.com/

### Link to download/purchase page

https://creativemarket.com/stefan.djokic/168443-Oak-Clean-Responsive-Ghost-Theme

### Number of columns

2

**Comment by dbalders** [comment]
Updated (finally, geez sorry about that). Also, I really like this theme. Very well done.

**Comment by Djokic** [comment]
Thank you. I'm very glad that you like it. :)

-----Original Message-----
