### ISSUE TITLE
Supra

### ISSUE THREAD

**Issue by seanrussell** [HowtoGhost/allghostthemes#56]
### Theme Name
Supra

### Theme Description

Supra is a minimal theme built for use with the Ghost blogging platform. It features a content focused design with subtle effects that are meant to provide a comfortable and engaging experience.

### Link to your live demo

http://supra-theme.herokuapp.com

### Link to download/purchase page

https://gumroad.com/l/supra-theme

### Number of columns

1

**Comment by dbalders** [comment]
@seanrussell Sorry, i know its been forever since you posted this, but do you have a new demo link? that one and http://supra-theme.seandrussell.com/ from your gumroad page don't work currently. Will get it up asap if you have a new one. Sorry again for taking so long.
