### ISSUE TITLE
GhostBox

### ISSUE THREAD

**Issue by dylmanning** [HowtoGhost/allghostthemes#57]
### Theme Name

GhostBox

### Theme Description

portfolio theme based off a codrops article

### Link to your live demo

http://dmanning.com.au/ghostbox

### Link to download/purchase page

https://github.com/dylush/GhostBox

### Number of columns

x

**Comment by dbalders** [comment]
@dylmanning Sorry for taking so long, I know its been forever since you posted this, but the link to your demo is down. Do you happen to have a new demo link? I will get the theme up asap if you have a new link I can use. Thanks and sorry again

**Comment by dylmanning** [comment]
@dbalders thanks, link is fixed at the same address.
