### ISSUE TITLE
Purely

### ISSUE THREAD

**Issue by seanrussell** [HowtoGhost/allghostthemes#59]
### Theme Name

Purely

### Theme Description

Purely is a minimal theme built for Ghost that uses the Materializecss CSS framework to achieve a Material Design inspired aesthetic.

This theme supports all of the features of the latest Ghost release, including but not limited to post cover images, tag and author pages, previous and next post links, multi author support and more.
your theme description

### Link to your live demo

http://purely-seandrussell.rhcloud.com/

### Link to download/purchase page

https://gumroad.com/l/purely-theme

### Number of columns

2

**Comment by dbalders** [comment]
@seanrussell same as Supra with this one
