### ISSUE TITLE
Guapo

### ISSUE THREAD

**Issue by misterGF** [HowtoGhost/allghostthemes#98]
### Theme Name
Guapo

### Theme Description
A handsome Ghost theme for those with exquisite taste.

### Link to your live demo
http://gferreira.me/

### Link to download/purchase page
http://gferreira.me/get-guapo/

### Number of columns
1

**Comment by andyboutte** [comment]
Hey @misterGF.  I was just working on getting your theme added to allghostthemes.com but there is an issue with your domain.  Let me know when the issue is fixed and I will get your theme added.

**Comment by misterGF** [comment]
Hey @andyboutte. It's back up. Recently changed DNS providers and had some things to work out.
Thanks!
